# Generated by Django 3.2.5 on 2021-07-21 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_ski',
            new_name='votes_to_skip',
        ),
    ]
